everest/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('everest.views.general',
                       url(r'^$', 'home', name='home'),
                       url(r'^lesson/(?P<lesson>[0-9]+)$', 'view_lesson', name='view_lesson'),
                       url(r'^profile/(?P<username>[a-zA-Z0-9_]+)$', 'view_user', name='view_user'),
                       url(r'^profile/$', 'view_self', name='view_self'),
                       # Registration urls
                       url(r'^register$', 'register', name='register'),
                       url(r'^confirm/(?P<username>[a-zA-Z0-9_]+)/(?P<token>.*)$', 'confirm', name='confirm_account'),
                       url(r'^send-reset/(?P<username>[a-zA-Z0-9_]+)/(?P<token>.*)$', 'reset_password', name='reset_password'),
                       url(r'^reset-password$', 'reset_form', name='reset_form'),
                       )

urlpatterns += patterns('everest.views.teacher',
                        url(r'^teacher/create-lesson$', 'create_lesson', name='create_lesson'),
                        url(r'^teacher/edit-lesson/(?P<lesson>[0-9]+)$', 'edit_lesson', name='edit_lesson'),
                        url(r'^ajax/teacher/create-sentence/(?P<lesson>[0-9]+)$', 'create_sentence',
                            name='create_sentence'),
                        url(r'^teacher/add-sentence/(?P<sentence>[0-9]+)/(?P<lesson>[0-9]+)$', 'add_sentence',
                            name='add_sentence'),
                        url(r'download/lesson/(?P<lesson>[0-9]+)$', 'download_lesson', name='download_lesson')
                        )

urlpatterns += patterns('everest.views.profile',
                        url(r'^manage_account$', 'manage_account', name='manage_account'),
                        url(r'^ajax/change-personal$', 'change_personal', name='change_personal'),
                        url(r'^ajax/change-password$', 'change_password', name='change_password'),
                        url(r'^ajax/change-picture$', 'change_picture', name='change_picture'),
                        )

urlpatterns += patterns('everest.views.sentence',
                        url(r'^sentence/(?P<sentence>[0-9]+)$', 'view_sentence', name='view_sentence'),
                        url(r'^sentence/(?P<sentence>[0-9]+)/record/english$', 'record_english', name='record_english'),
                        url(r'^sentence/(?P<sentence>[0-9]+)/record/nepali$', 'record_nepali', name='record_nepali'),
                        url(r'^sentence/(?P<sentence>[0-9]+)/recording$', 'upload_audio', name='submit_recording'),
                        url(r'^sentence/(?P<sentence>[0-9]+)/translation$', 'submit_translation',
                            name='submit_translation'),
                        )

urlpatterns += patterns('everest.views.delete',
                        url(r'^delete/translation/(?P<translation>[0-9]+)$', 'del_translation', name='del_translation'),
                        url(r'^delete/english-audio/(?P<audio>[0-9]+)$', 'del_englishaudio', name='del_englishaudio'),
                        url(r'^delete/nepali-audio/(?P<audio>[0-9]+)$', 'del_nepaliaudio', name='del_nepaliaudio'),
                        url(r'^ajax/delete/sentence/(?P<sentence>[0-9]+)/(?P<lesson>[0-9]+)$', 'del_sentence',
                            name='del_sentence'),
                        url(r'^delete-lesson/(?P<lesson>[0-9]+)$', 'del_lesson', name='del_lesson')
                        )

urlpatterns += patterns('everest.views.search',
                        url(r'^sentences/$', 'search_sentences', name='search_sentences'),
                        url(r'^sentences/needs-translation', 'search_needs_translation',
                            name='search_needs_translation'),
                        url(r'^sentences/needs-english-audio$', 'search_needs_engaudio', name='search_needs_engaudio'),
                        url(r'^lessons/$', 'search_lessons', name='search_lessons'),
                        url(r'^lessons/(?P<username>[a-zA-Z0-9_]+)$', 'search_user_lessons',
                            name='search_user_lessons'),
                        url(r'^lessons/my-lessons', 'search_my_lessons', name='search_my_lessons'),
                        url(r'^users/$', 'search_users', name='search_users'),
                        )

urlpatterns += patterns('',
                        url(r'^login$', 'django.contrib.auth.views.login',
                            {'template_name': 'everest/signin_register/login.html'}, name='login_page'),
                        # Route to logout a user and send them back to the login page
                        url(r'^logout$', 'django.contrib.auth.views.logout_then_login', name='logout'),
                        )

webapps/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
                       url(r'^', include('everest.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       # url(r'^search/', include('haystack.urls')),
                       )

everest/models.py
import uuid

from django.db import models


# User class for built-in authentication module
from django.contrib.auth.models import User


class Sentence(models.Model):
    english = models.CharField(max_length=200, unique=True)
    created = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(User)

    def __unicode__(self):
        return self.english


def picture_path(instance, filename):
    return 'userpic/{0}{1}{2}'.format(instance.username, uuid.uuid4(), filename)


class UserProfile(models.Model):
    userkey = models.OneToOneField(User, related_name='profile')
    bio = models.CharField(max_length=430, blank=True)
    image = models.ImageField(upload_to="pictures", blank=True, null=True)
    ESL_TEACHER = 'E'
    TRANSLATOR = 'T'
    OTHER = 'O'
    USER_TYPES = (
        (ESL_TEACHER, 'ESL teacher'),
        (TRANSLATOR, 'Translator'),
        (OTHER, 'Other')
    )
    user_type = models.CharField(max_length=1, choices=USER_TYPES)


class Lesson(models.Model):
    title = models.CharField(max_length=50)
    sentences = models.ManyToManyField(Sentence, related_name='lessons', symmetrical=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(User, related_name='lessons')

    def __unicode__(self):
        return self.title
        # link to mp3


def nepali_path(instance, filename):
    return 'nepali/{0}{1}'.format(uuid.uuid4(), filename)


def english_path(instance, filename):
    return 'english/{0}{1}'.format(uuid.uuid4(), filename)


class NepaliAudio(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(User, related_name='nep_recordings')
    sentence = models.ForeignKey(Sentence, related_name='nep_audio')
    audio = models.FileField(upload_to=nepali_path)


class EnglishAudio(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(User, related_name='eng_recordings')
    sentence = models.ForeignKey(Sentence, related_name='eng_audio')
    audio = models.FileField(upload_to=english_path)


class Translation(models.Model):
    nepali = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(User, related_name='translations')
    sentence = models.ForeignKey(Sentence, related_name='translations')

    def __unicode__(self):
        return self.nepali

everest/views/delete.py
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse

from everest.forms import *


@login_required
@transaction.atomic
def del_translation(request, translation):
    was_deleted = False
    translation = get_object_or_404(Translation, pk=translation)
    sentence = translation.sentence
    if request.method == 'POST' and request.user == translation.creator:
        translation.delete()
        was_deleted = cleanup(sentence)
    if was_deleted:
        return redirect(reverse('search_sentences'))
    context = {'sentence': sentence}
    return render(request, 'everest/sentence/sentence.html', context)


@login_required
@transaction.atomic
def del_englishaudio(request, audio):
    was_deleted = False
    audio = get_object_or_404(EnglishAudio, pk=audio)
    sentence = audio.sentence
    if request.method == 'POST' and request.user == audio.creator:
        audio.delete()
        was_deleted = cleanup(sentence)

    if was_deleted:
        return redirect(reverse('search_sentences'))
    context = {'sentence': sentence}
    return render(request, 'everest/sentence/sentence.html', context)


@login_required
@transaction.atomic
def del_nepaliaudio(request, audio):
    was_deleted = False
    audio = get_object_or_404(NepaliAudio, pk=audio)
    sentence = audio.sentence
    if request.method == 'POST' and request.user == audio.creator:
        audio.delete()
        was_deleted = cleanup(sentence)

    if was_deleted:
        return redirect(reverse('search_sentences'))
    context = {'sentence': sentence}
    return render(request, 'everest/sentence/sentence.html', context)


"""
Edit Lesson View Deletions
"""


@login_required
@transaction.atomic
def del_sentence(request, sentence, lesson):
    sentence = get_object_or_404(Sentence, pk=sentence)
    lesson = get_object_or_404(Lesson, pk=lesson)
    if request.method == 'POST' and request.user == lesson.creator:
        lesson.sentences.remove(sentence)
        lesson.save()
        cleanup(sentence)
    context = {'lesson': lesson}
    return render(request, 'everest/lesson/sentence_table_del.html', context)


@login_required
@transaction.atomic
def del_lesson(request, lesson):
    lesson = get_object_or_404(Lesson, pk=lesson)
    if request.method == 'POST' and request.user == lesson.creator:
        to_clean = list(lesson.sentences.all())
        lesson.delete()
        for sentence in to_clean:
            cleanup(sentence)

    return redirect(reverse('search_my_lessons'))


# returns True if deleted sentence
def cleanup(sentence):
    if sentence.translations.all() or sentence.eng_audio.all() or sentence.nep_audio.all() or sentence.lessons.all():
        return False
    sentence.delete()
    return True

everest/views/general.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from django.core.urlresolvers import reverse
from django.core.mail import send_mail
from django.template.loader import render_to_string

# Decorator to use built-in authentication system
from django.contrib.auth.decorators import login_required

# Used to create and manually log in a user
from django.contrib.auth.tokens import default_token_generator

from django.db import transaction
from everest.forms import *

# "home" is his/her lessons for an ESL teacher, sentences needing translations for
# a translator, and all available lessons for anyone else
def home(request):
    if request.user.is_authenticated():
        usertype = request.user.profile.user_type
        if usertype == "E":
            return redirect('search_my_lessons')
        elif usertype == "T":
            return redirect('search_needs_translation')
        else:
            return redirect('search_lessons')
    else:
        return render(request, 'everest/index.html', {})


def view_lesson(request, lesson):
    lesson = get_object_or_404(Lesson, pk=lesson)
    context = {'lesson': lesson}
    return render(request, 'everest/lesson/lesson.html', context)


@login_required
def view_self(request):
    return redirect('view_user', username=request.user.username)


def view_user(request, username):
    user = get_object_or_404(User, username=username)
    profile = user.profile
    context = {'profile': profile}
    if profile.user_type == "E":
        context["lessons"] = profile.userkey.lessons.all
        context["sentences"] = None
    elif profile.user_type == "T":
        context["lessons"] = None
        s = set([translation.sentence for translation in user.translations.all()])
        s = s.union(set([recording.sentence for recording in user.nep_recordings.all()]))
        context["sentences"] = s
    return render(request, 'everest/profile/profile.html', context)


@transaction.atomic
def register(request):
    context = {}
    # Just display the registration form if this is a GET request
    if request.method == 'GET':
        context['form'] = RegisterForm()
        return render(request, 'everest/signin_register/register.html', context)
    form = RegisterForm(request.POST.copy())
    if not form.is_valid():
        form.data['password'] = None
        form.data['password2'] = None
        context['form'] = form
        return render(request, 'everest/signin_register/register.html', context)
    # everything is okay, register
    username = form.cleaned_data['username']
    password = form.cleaned_data['password1']
    new_user = User.objects.create_user(
        username=username,
        password=password,
        first_name=form.cleaned_data['first_name'],
        last_name=form.cleaned_data['last_name'],
        email=form.cleaned_data['email'],
    )
    new_user.is_active = False
    new_user.save()
    profile = UserProfile.objects.create(
        userkey=new_user,
        bio='',
        user_type=form.cleaned_data['user_type'],
    )
    profile.save()

    token = default_token_generator.make_token(new_user)
    url = request.get_host() + reverse('confirm_account', args=(new_user.username, token))
    context = {'user': new_user, 'url': url}
    email_html = render_to_string('email/register.txt', context)
    email_text = render_to_string('email/register.html', context)

    send_mail(subject="Verify your email address",
              html_message=email_html,
              message=email_text,
              from_email="everesteslwebmaster@gmail.com",
              recipient_list=[new_user.email])
    return render(request, 'everest/signin_register/confirm_sent.html', context)


@transaction.atomic
def confirm(request, username, token):
    user = get_object_or_404(User, username=username)
    if not user.is_active:
        if not default_token_generator.check_token(user, token):
            raise Http404("Incorrect token")
        user.is_active = True
        user.save()
    return render(request, 'everest/signin_register/account_confirmed.html', {'user': user})


def reset_form(request):
    context = {}
    if request.POST:
        form = ResetForm(request.POST)
        if form.is_valid():
            users = User.objects.filter(username=form.cleaned_data['username'])
            if users.all():
                send_reset_email(request, users[0])
                context['requestor'] = users[0]
                return render(request, 'everest/signin_register/reset_sent.html', context)
            else:
                context['error'] = 'Username does not exist'
        else:
            context['form'] = form
    return render(request, 'everest/signin_register/reset_request.html', context)


def send_reset_email(request, user):
    token = default_token_generator.make_token(user)
    url = request.get_host() + reverse('reset_password', args=(user.username, token))
    context = {'user': user, 'url': url}
    email_html = render_to_string('email/reset.txt', context)
    email_text = render_to_string('email/reset.html', context)

    send_mail(subject="Information regarding your Everest account",
              html_message=email_html,
              message=email_text,
              from_email="everesteslwebmaster@gmail.com",
              recipient_list=[user.email])


@transaction.atomic
def reset_password(request, username, token):
    user = get_object_or_404(User, username=username)
    if not default_token_generator.check_token(user, token):
        raise Http404("Incorrect token")
    random_pass = User.objects.make_random_password()
    send_password_email(user, random_pass)
    user.set_password(random_pass)
    user.save()
    return render(request, 'everest/signin_register/password_sent.html', {'requestor': user})


def send_password_email(user, password):
    context = {'user': user, 'password': password}
    email_html = render_to_string('email/password.txt', context)
    email_text = render_to_string('email/password.html', context)

    send_mail(subject="Information regarding your Everest account",
              html_message=email_html,
              message=email_text,
              from_email="everesteslwebmaster@gmail.com",
              recipient_list=[user.email])

everest/views/record.py
from django.shortcuts import render
from django.http import HttpResponse
import json


def home(request):
    return render(request, 'everest/record.html', {})

def upload(request):
    print request.POST
    print request.FILES
    print request.GET
    #print request
    if request.POST:
        #print request.POST
        #print blob
        #print request.FILES
        pass
    to_json = {'yes': "hi"}
    return HttpResponse(json.dumps(to_json), content_type='application/json')

everest/templates/everest/profile/edit_password_form.html
<form class="form-horizontal" role="form" action="{% url 'change_password' %}" method="post"> {% csrf_token %}
    <div class="form-group">
        <div class="col-lg-2"></div>
        <div class="col-md-8">
            {{ form.non_field_errors }}
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-2"></div>
        <div class="col-md-8">
            {% if wrong_password %}
                <ul class="errorlist">
                    <li>Current password is not correct</li>
                </ul>
            {% endif %}
            {{ form.current.errors }}
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">Current:</label>

        <div class="col-md-8">
            <input class="form-control" name="current" type="password" value="">
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-2"></div>
        <div class="col-md-8">
            {{ form.password1.errors }}
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">New:</label>

        <div class="col-md-8">
            <input class="form-control" name="password1" type="password" value="">
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-2"></div>
        <div class="col-md-8">
            {{ form.password2.errors }}
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">Confirm:</label>

        <div class="col-md-8">
            <input class="form-control" name="password2" type="password" value="">
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label"></label>

        <div class="col-md-8">
            <input type="submit" class="btn btn-primary" value="Change Password">
        </div>
    </div>
</form>

everest/templates/everest/profile/edit_personal_form.html
<form class="form-horizontal" role="form" action="{% url 'change_personal' %}" method="post"> {% csrf_token %}
    <div class="form-group">
        <div class="col-lg-2"></div>
        <div class="col-md-8">
            {{ form.non_field_errors }}
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-2"></div>
        <div class="col-md-8">
            {{ form.first_name.errors }}
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">First name:</label>

        <div class="col-lg-8">
            <input class="form-control" name="first_name" type="text" value="{{ request.user.first_name }}">
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-2"></div>
        <div class="col-md-8">
            {{ form.last_name.errors }}
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">Last name:</label>

        <div class="col-lg-8">
            <input class="form-control" name="last_name" type="text" value="{{ request.user.last_name }}">
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-2"></div>
        <div class="col-md-8">
            {{ form.email.errors }}
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">Email:</label>

        <div class="col-lg-8">
            <input class="form-control" name="email" type="text" value="{{ request.user.email }}">
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-2"></div>
        <div class="col-md-8">
            {{ form.user_type.errors }}
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">Account Type:</label>

        <div class="col-lg-8">
            <div class="ui-select">
                <select name="user_type" class="form-control">
                    <option value="E" {% if request.user.profile.user_type == "E" %}selected="selected"{% endif %}>ESL
                        Teacher
                    </option>
                    <option value="T" {% if request.user.profile.user_type == "T" %}selected="selected"{% endif %}>
                        Translator
                    </option>
                    <option value="O" {% if request.user.profile.user_type == "O" %}selected="selected"{% endif %}>
                        Other
                    </option>
                </select>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-2"></div>
        <div class="col-md-8">
            {{ form.bio.errors }}
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">Bio:</label>

        <div class="col-lg-8">
            <textarea class="form-control" type="textarea" name="bio" rows="2">{{ request.user.profile.bio }}</textarea>
        </div>
    </div>

    <div class="form-group">
        <label class="col-md-2 control-label"></label>

        <div class="col-md-8">
            <input type="submit" class="btn btn-primary" value="Save Changes">
        </div>
    </div>
</form>

everest/templates/everest/profile/edit_profile.html
{% extends "everest/base.html" %}

{% block title %}Manage Account{% endblock %}

{% block pageheader %} Manage Account {% endblock %}

{% block content %}
    <div class="row">
        <!-- left column -->
        <div class="col-md-3">
            <div class="text-center">
                <p class="subtitle">Change profile picture</p>
                {% if request.user.profile.image %}
                    <img id="user-picture" src="{{ request.user.profile.image.url }}" class="avatar img-circle"
                         height="150px" width="150px" alt="avatar">
                {% else %}
                    <img id="user-picture" src="http://placehold.it/150x150" class="avatar img-circle" height="150px"
                         width="150px" alt="avatar">
                {% endif %}
                <div class="smallskip"></div>
                <form id="picture-form" class="form-horizontal" role="form" action="{% url 'change_picture' %}"
                      method="post"> {% csrf_token %}
                    <div id="picture-errors"></div>
                    <input type="file" id="picture-input" name="image" accept="image/*" class="form-control">
                    <input type="submit" class="btn" value="Upload file">
                </form>
            </div>
        </div>

        <!-- edit form column -->
        <div class="col-md-9 personal-info">
            <p class="subtitle">Personal info</p>

            <div id="personal-form">
                {% include 'everest/profile/edit_personal_form.html' %}
            </div>
            <div class="smallskip"></div>

            <p class="subtitle">Change password</h3>

            <div id="password-form">
                {% include 'everest/profile/edit_password_form.html' %}
            </div>
        </div>
    </div>
    <hr>
{% endblock %}



{% block scripts %}
    <script>
        $("#personal-form").on("submit", function (e) {
            console.log("hai");
            $.ajax({
                type: "POST",
                url: $("#personal-form > form").attr('action'),
                data: $("#personal-form > form").serialize(),
                success: function (response) {
                    $("#personal-form").html(response);
                }
            });
            e.preventDefault();
            return false;
        });
    </script>
    <script>
        $("#password-form").on("submit", function (e) {
            console.log("hai");
            $.ajax({
                type: "POST",
                url: $("#password-form > form").attr('action'),
                data: $("#password-form > form").serialize(),
                success: function (response) {
                    $("#password-form").html(response);
                }
            });
            e.preventDefault();
            return false;
        });
    </script>
    <script>
        $("#picture-form").on("submit", function (e) {
            console.log("hai");
            var formData = new FormData($(this)[0]);
            $.ajax({
                type: "POST",
                url: $("#picture-form").attr('action'),
                data: formData,
                contentType: false,
                processData: false,
                success: function (response) {
                    console.log(response);
                    if (response['image'] != '') {
                        console.log("should replace");
                        $("#user-picture").attr("src", response['image']);
                    }
                    if (response['error'] != '') {
                        $("#picture-errors").html(response['error']);
                    }
                    $("#picture-form").find("input").blur();
                    var pic_input = $("#picture-input");
                    pic_input.replaceWith(pic_input.clone());
                }
            });
            e.preventDefault();
            return false;
        });
    </script>
{% endblock %}

everest/templates/everest/profile/profile.html
{% extends "everest/base.html" %}

{% block title %} {{ profile.userkey | capfirst }}'s Profile {% endblock %}
{% block pageheader %}
    {{ profile.userkey.first_name | capfirst }} {{ profile.userkey.last_name | capfirst }} ({{ profile.userkey }}),
    {{ profile.get_user_type_display }}
{% endblock %}

{% block content %}


    <div class="row">
        <div class="col-md-8">
            <div class="panel panel-default">
                <div class="panel-body">
                    <p class="subtitle">Bio</p>
                    {% if profile.bio %}
                        {{ profile.bio }}
                    {% else %}
                        <p class="subtletext">{{ profile.userkey.first_name | capfirst }} {{ profile.userkey.last_name | capfirst }}
                            has no bio.</p>
                    {% endif %}
                    <div class="smallskip"></div>
                </div>
            </div>
        </div>

        <div class="col-md-3 col-md-offset-1">
            {% if profile.image %}
                <img id="user-picture" src="{{ profile.image.url }}" class="avatar img-circle"
                     height="150px" width="150px" alt="avatar">
                <p class="subtletext">{{ profile.userkey.first_name | capfirst }} {{ profile.userkey.last_name | capfirst }}
                    ({{ profile.userkey }})</p>
            {% else %}
                <img id="user-picture" src="http://placehold.it/150x150" class="avatar img-circle" height="150px"
                     width="150px" alt="avatar">
                <p class="subtletext">{{ profile.userkey.first_name | capfirst }} {{ profile.userkey.last_name | capfirst }}
                    has no picture.</p>
            {% endif %}
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-body">
            {% if profile.user_type == "E" %}
                <p class="subtitle">{{ profile.userkey.first_name | capfirst }} {{ profile.userkey.last_name | capfirst }}'s
                    Lessons</p>
                {% include "everest/lists/lesson_table.html" with lessons=lessons %}
            {% elif profile.user_type == "T" %}
                <p class="subtitle">{{ profile.userkey.first_name | capfirst }} {{ profile.userkey.last_name | capfirst }}'s
                    Translations</p>
                {% include "everest/lists/sentence_table.html" with sentences=sentences %}
            {% endif %}
        </div>
    </div>

{% endblock %}